# Site settings
title: The long road to internet
email: melissacor3lfuss@gmail.com
description: My journey from n00b to not n00b
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://melissakaulfuss.com" # the base hostname & protocol for your site
twitter_username: MelissaKaulfuss
github_username:  MelissaKaulfuss

# Build settings
markdown: kramdown
