# Site settings
title: The long road to internet
email: melissacor3lfuss@gmail.com
description: My journey from n00b to not n00b
<<<<<<< 4908aa9ebd153800396accafb58269e88fd4d19f
baseurl: "" # the subpath of your site, e.g. /blog/
url: "melissakaulfuss.com" # the base hostname & protocol for your site
=======
baseurl: "/my_blog" # the subpath of your site, e.g. /blog/
url: "http://melissakaulfuss.com" # the base hostname & protocol for your site
>>>>>>> Mess with config file
twitter_username: MelissaKaulfuss
github_username:  MelissaKaulfuss

# Build settings
markdown: kramdown
